# Generated by Django 4.2.4 on 2023-08-20 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing_socity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing_socity",
            name="sec_from",
            field=models.DateField(default=datetime.date(2023, 8, 20)),
        ),
    ]
