# Generated by Django 4.2.4 on 2023-08-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing_socity", "0004_housing_socity_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housing_socity",
            name="sec_from",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 27, 6, 42, 45, 919112, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
