# Generated by Django 4.2.4 on 2023-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing_socity", "0007_alter_housing_socity_sec_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housing_socity",
            name="sec_from",
            field=models.DateField(auto_now_add=True),
        ),
    ]
