# Generated by Django 4.2.4 on 2023-08-31 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("housing_socity", "0008_alter_housing_socity_sec_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("des", models.TextField()),
                ("date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("pic", models.FileField(blank=True, null=True, upload_to="event")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="housing_socity.housing_socity",
                    ),
                ),
            ],
        ),
    ]
