# Generated by Django 4.2.4 on 2023-09-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0005_rename_password_member_password"),
        ("housing_socity", "0009_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("des", models.TextField()),
                ("notice_on", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                (
                    "send_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="housing_socity.housing_socity",
                    ),
                ),
                (
                    "send_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.member"
                    ),
                ),
            ],
        ),
    ]
