# Generated by Django 4.2.4 on 2023-09-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0007_delete_main"),
        ("housing_socity", "0012_alter_complain_solve_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sell", models.BooleanField(default=False)),
                ("rent", models.BooleanField(default=False)),
                ("message", models.TextField()),
                (
                    "owner_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.member"
                    ),
                ),
            ],
        ),
    ]
