# Generated by Django 4.2.4 on 2023-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="res_type",
            field=models.CharField(
                choices=[("Owner", "Owner"), ("Rent", "Rent")],
                default="owner",
                max_length=20,
            ),
        ),
    ]
