# Generated by Django 4.2.4 on 2023-09-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0006_main"),
    ]

    operations = [
        migrations.DeleteModel(
            name="main",
        ),
    ]
